# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entities.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65ntities.proto\"\x06\n\x04Void\"\x16\n\x06\x43lient\x12\x0c\n\x04name\x18\x01 \x01(\t\"G\n\x07Message\x12\x13\n\x0bsender_name\x18\x01 \x01(\t\x12\x14\n\x0cmessage_text\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\x32Y\n\x04\x43hat\x12\x17\n\x04send\x12\x08.Message\x1a\x05.Void\x12\x1c\n\x07receive\x12\x05.Void\x1a\x08.Message0\x01\x12\x1a\n\x08register\x12\x07.Client\x1a\x05.Voidb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entities_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VOID']._serialized_start=18
  _globals['_VOID']._serialized_end=24
  _globals['_CLIENT']._serialized_start=26
  _globals['_CLIENT']._serialized_end=48
  _globals['_MESSAGE']._serialized_start=50
  _globals['_MESSAGE']._serialized_end=121
  _globals['_CHAT']._serialized_start=123
  _globals['_CHAT']._serialized_end=212
# @@protoc_insertion_point(module_scope)
